LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
Loading `train_dataloader` to estimate number of stepping batches.
/home/medici/Documents/Projects/CSSL/.venv/lib/python3.12/site-packages/pytorch_lightning/loops/fit_loop.py:310: The number of training batches (40) is smaller than the logging interval Trainer(log_every_n_steps=50). Set a lower value for log_every_n_steps if you want to see logs for the training epoch.
Training tasks: 0it [00:02, ?it/s]
Scenerio:   0%|                                                                                                              | 0/1 [00:05<?, ?it/s]
Traceback (most recent call last):
  File "/home/medici/Documents/Projects/CSSL/train.py", line 141, in <module>
    main(args)
  File "/home/medici/Documents/Projects/CSSL/train.py", line 90, in main
    trainer.fit(model, train_pretrain_loader)
  File "/home/medici/Documents/Projects/CSSL/.venv/lib/python3.12/site-packages/pytorch_lightning/trainer/trainer.py", line 561, in fit
    call._call_and_handle_interrupt(
  File "/home/medici/Documents/Projects/CSSL/.venv/lib/python3.12/site-packages/pytorch_lightning/trainer/call.py", line 48, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/medici/Documents/Projects/CSSL/.venv/lib/python3.12/site-packages/pytorch_lightning/trainer/trainer.py", line 599, in _fit_impl
    self._run(model, ckpt_path=ckpt_path)
  File "/home/medici/Documents/Projects/CSSL/.venv/lib/python3.12/site-packages/pytorch_lightning/trainer/trainer.py", line 988, in _run
    self.strategy.setup(self)
  File "/home/medici/Documents/Projects/CSSL/.venv/lib/python3.12/site-packages/pytorch_lightning/strategies/strategy.py", line 159, in setup
    self.setup_optimizers(trainer)
  File "/home/medici/Documents/Projects/CSSL/.venv/lib/python3.12/site-packages/pytorch_lightning/strategies/strategy.py", line 139, in setup_optimizers
    self.optimizers, self.lr_scheduler_configs = _init_optimizers_and_lr_schedulers(self.lightning_module)
                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/medici/Documents/Projects/CSSL/.venv/lib/python3.12/site-packages/pytorch_lightning/core/optimizer.py", line 180, in _init_optimizers_and_lr_schedulers
    optim_conf = call._call_lightning_module_hook(model.trainer, "configure_optimizers", pl_module=model)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/medici/Documents/Projects/CSSL/.venv/lib/python3.12/site-packages/pytorch_lightning/trainer/call.py", line 176, in _call_lightning_module_hook
    output = fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^
  File "/home/medici/Documents/Projects/CSSL/cssl/models/base_ssl.py", line 105, in configure_optimizers
    optimizer, scheduler = self.get_optimizer(params, params_no_weight_decay)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/medici/Documents/Projects/CSSL/cssl/models/base_ssl.py", line 66, in get_optimizer
    "scheduler": CosineWarmupScheduler(
                 ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/medici/Documents/Projects/CSSL/.venv/lib/python3.12/site-packages/lightly/utils/scheduler.py", line 185, in __init__
    super().__init__(
TypeError: LambdaLR.__init__() got an unexpected keyword argument 'verbose'
